<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4dXjBlw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4dXjBlw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4dXjBlw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4dXjBlw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4dXjBlw\App_KernelDevDebugContainer([
    'container.build_hash' => '4dXjBlw',
    'container.build_id' => 'e4402d66',
    'container.build_time' => 1655058801,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4dXjBlw');
