<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVeoIckY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVeoIckY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVeoIckY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVeoIckY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVeoIckY\App_KernelDevDebugContainer([
    'container.build_hash' => 'VeoIckY',
    'container.build_id' => '969b6447',
    'container.build_time' => 1654969328,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVeoIckY');
