<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN6admyY\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN6admyY/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerN6admyY.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerN6admyY\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerN6admyY\App_KernelDevDebugContainer([
    'container.build_hash' => 'N6admyY',
    'container.build_id' => 'fa0e0908',
    'container.build_time' => 1655064795,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerN6admyY');
